// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEW2-hIYkFt81_xag4glZR3DLDoFj0FNk',
    appId: '1:299267798038:web:12b6d1e0a4a9f4dc4b3137',
    messagingSenderId: '299267798038',
    projectId: 'nbi-signup',
    authDomain: 'nbi-signup.firebaseapp.com',
    storageBucket: 'nbi-signup.firebasestorage.app',
    measurementId: 'G-DZQ5WM8Q29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9qqb1A1Jd3Od_vB4dDxp3FX5m1niM270',
    appId: '1:299267798038:android:ae3082c3af240b424b3137',
    messagingSenderId: '299267798038',
    projectId: 'nbi-signup',
    storageBucket: 'nbi-signup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp7JHbDdyKelEzxfJGyII-N_XGnJR3fsA',
    appId: '1:299267798038:ios:e2171a7fabce631b4b3137',
    messagingSenderId: '299267798038',
    projectId: 'nbi-signup',
    storageBucket: 'nbi-signup.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp7JHbDdyKelEzxfJGyII-N_XGnJR3fsA',
    appId: '1:299267798038:ios:e2171a7fabce631b4b3137',
    messagingSenderId: '299267798038',
    projectId: 'nbi-signup',
    storageBucket: 'nbi-signup.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEW2-hIYkFt81_xag4glZR3DLDoFj0FNk',
    appId: '1:299267798038:web:dc92b34097c060f94b3137',
    messagingSenderId: '299267798038',
    projectId: 'nbi-signup',
    authDomain: 'nbi-signup.firebaseapp.com',
    storageBucket: 'nbi-signup.firebasestorage.app',
    measurementId: 'G-12B8KM4GQW',
  );
}
